config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  resources :teams
  resources :athletes
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/athlete.rb
class Athlete < ApplicationRecord
  belongs_to :team
end

app/models/team.rb
class Team < ApplicationRecord
  has_many :athletes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/athletes_controller.rb
class AthletesController < ApplicationController
  before_action :set_athlete, only: %i[ show edit update destroy ]

  # GET /athletes or /athletes.json
  def index
    @athletes = Athlete.all
  end

  # GET /athletes/1 or /athletes/1.json
  def show
  end

  # GET /athletes/new
  def new
    @athlete = Athlete.new
  end

  # GET /athletes/1/edit
  def edit
  end

  # POST /athletes or /athletes.json
  def create
    @athlete = Athlete.new(athlete_params)

    respond_to do |format|
      if @athlete.save
        format.html { redirect_to athlete_url(@athlete), notice: "Athlete was successfully created." }
        format.json { render :show, status: :created, location: @athlete }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @athlete.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /athletes/1 or /athletes/1.json
  def update
    respond_to do |format|
      if @athlete.update(athlete_params)
        format.html { redirect_to athlete_url(@athlete), notice: "Athlete was successfully updated." }
        format.json { render :show, status: :ok, location: @athlete }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @athlete.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /athletes/1 or /athletes/1.json
  def destroy
    @athlete.destroy!

    respond_to do |format|
      format.html { redirect_to athletes_url, notice: "Athlete was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_athlete
      @athlete = Athlete.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def athlete_params
      params.require(:athlete).permit(:nome, :numero, :posicao, :team_id, :tipo_atleta)
    end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :set_team, only: %i[ show edit update destroy ]

  # GET /teams or /teams.json
  def index
    @teams = Team.all
  end

  # GET /teams/1 or /teams/1.json
  def show
  end

  # GET /teams/new
  def new
    @team = Team.new
  end

  # GET /teams/1/edit
  def edit
  end

  # POST /teams or /teams.json
  def create
    @team = Team.new(team_params)

    respond_to do |format|
      if @team.save
        format.html { redirect_to team_url(@team), notice: "Team was successfully created." }
        format.json { render :show, status: :created, location: @team }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teams/1 or /teams/1.json
  def update
    respond_to do |format|
      if @team.update(team_params)
        format.html { redirect_to team_url(@team), notice: "Team was successfully updated." }
        format.json { render :show, status: :ok, location: @team }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teams/1 or /teams/1.json
  def destroy
    @team.destroy!

    respond_to do |format|
      format.html { redirect_to teams_url, notice: "Team was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_team
      @team = Team.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def team_params
      params.require(:team).permit(:nome, :endereco, :athletes_id, :historia, :infos, :titulo, :titulo2, :titulo3, :titulo4, :titulo5)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/athletes_helper.rb
module AthletesHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/athletes/_athlete.html.erb
<div id="<%= dom_id athlete %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Nome:</strong>
    <%= athlete.nome %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Numero:</strong>
    <%= athlete.numero %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Posicao:</strong>
    <%= athlete.posicao %>
  </p>
  <p class="my-5">
    <strong class="block font-medium mb-1">Time:</strong>
    <%= athlete.team_id %>
  </p>
  <p class="my-5">
    <strong class="block font-medium mb-1">Tipo atleta:</strong>
    <%= athlete.tipo_atleta %>
  </p>

</div>

app/views/athletes/_form.html.erb
<%= form_with(model: athlete, class: "contents") do |form| %>
  <% if athlete.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(athlete.errors.count, "error") %> prohibited this athlete from being saved:</h2>

      <ul>
        <% athlete.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :nome %>
    <%= form.text_field :nome, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :numero %>
    <%= form.number_field :numero, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :posicao %>
    <%= form.text_field :posicao, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>
  <div class="my-5">
    <%= form.label :team_id %>
    <%= form.text_field :team_id, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>
  <div class="my-5">
    <%= form.label :tipo_atleta %>
    <%= form.text_field :tipo_atleta, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "custom-button" %>
  </div>
<% end %>

app/views/athletes/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing athlete</h1>

  <%= render "form", athlete: @athlete %>

  <%= link_to "Show this athlete", @athlete, class: "custom-button" %>
  <%= link_to "Back to athletes", athletes_path, class: "custom-button" %>
</div>

app/views/athletes/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <% content_for :title, "Athletes" %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Athletes</h1>
    <%= link_to "New athlete", new_athlete_path, class: "custom-button" %>
  </div>

  <div id="athletes" class="min-w-full">
    <% @athletes.each do |athlete| %>
      <%= render athlete %>
      <p>
        <%= link_to "Show this athlete", athlete, class: "custom-button" %>
      </p>
    <% end %>
  </div>
</div>

app/views/athletes/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New athlete</h1>

  <%= render "form", athlete: @athlete %>

  <%= link_to "Back to athletes", athletes_path, class: "custom-button" %>
</div>

app/views/athletes/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @athlete %>

    <%= link_to "Edit this athlete", edit_athlete_path(@athlete), class: "custom-button" %>
    <%= link_to "Back to athletes", athletes_path, class: "custom-button" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this athlete", @athlete, method: :delete, class: "custom-button" %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SPFL</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= favicon_link_tag "sao_paulo_football_league.png" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <nav>
      <div class="navbar-container">
        <div class="navbar-logo">
          <img src="<%= asset_path("sao_paulo_football_league.png") %>" alt="Logo">
          <span class="font-semibold text-xl" style="color: #cbd5e0;">São Paulo Football League</span>
        </div>
        <ul class="navbar-menu">
          <li><a href="<%= root_path %>">Home</a></li>
          <li><a href="<%= teams_path %>">Times</a></li>
          <li><a href="<%= athletes_path %>">Atletas</a></li>
          <li><a href="#">Sobre</a></li>
          <li><a href="#">Contato</a></li>
        </ul>
      </div>
    </nav>

    <main class="container mx-auto mt-28 px-5">
      <%= yield %>
    </main>

    <% if controller.controller_name == 'welcome' %>
      <footer style="position: fixed; bottom: 0; left: 0; width: 100%; background-color: #1a202c; padding: 10px 0; text-align: center;">
        <div class="footer-container">
          <p class="footer-text">© <%= Time.now.year %> SPFL. | Desenvolvido por @rodrigosuco | Contato: <a href="mailto:rod1dev@proton.me">rod1dev@proton.me</a></p>
        </div>
      </footer>
    <% else %>
      <footer style="background-color: #1a202c; padding: 10px 0; text-align: center;">
        <div class="footer-container">
          <p class="footer-text">© <%= Time.now.year %> SPFL. | Desenvolvido por @rodrigosuco | Contato: <a href="mailto:rod1dev@proton.me">rod1dev@proton.me</a></p>
        </div>
      </footer>
    <% end %>
  </body>
</html>

app/views/welcome/index.html.erb
<div id="container-principal" class="flex items-start justify-between">
  <div class="flex items-start">
    <img id="logo-principal" src="<%= asset_path("sao_paulo_football_league.png") %>" alt="Imagem">
    <div class="ml-4">
      <h1 class="font-bold text-4xl">Bem-vindo à SPFL</h1>
      <h2>A maior e melhor liga estadual do Brasil.</h2>
      <h3>New football state.</h3>
    </div>
  </div>
  <div class="image-slider ml-16">
    <img id="fotos" src="<%= asset_path("org__caragua-ghostship-vs-corinthians-steamrollers-19775ac19858.jpg") %>" alt="Imagem 1" class="active">
    <img id="fotos" src="<%= asset_path("org__caragua-ghostship-vs-corinthians-steamrollers-b9d4cce6352c.jpg") %>" alt="Imagem 2">
    <img id="fotos" src="<%= asset_path("5e5a8874-275.jpg") %>" alt="Imagem 3">
  </div>
</div>